set -e
echo "=== Starting Post-Install Script ==="
sudo pacman -S --noconfirm \
mesa vulkan-intel intel-media-driver \
alacritty hyprland waybar wofi thunar tumbler \
xdg-desktop-portal xdg-desktop-portal-hyprland xorg-xwayland \
pipewire pipewire-pulse wireplumber sof-firmware alsa-utils pamixer \
brightnessctl playerctl grim slurp wl-clipboard polkit-gnome \
ttf-jetbrains-mono-nerd ttf-liberation \
firefox mako hyprpaper git

echo "=== Making Config Files ==="
mkdir -p ~/.config/hypr
mkdir -p ~/.config/alacritty
mkdir -p ~/.config/mako
mkdir -p ~/.config/fastfetch
cp /usr/share/hypr/hyprland.lua ~/.config/hypr/hyprland.lua

echo "--- writing to alacritty config ---"
cat << 'EOF' > ~/.config/alacritty/alacritty.toml
[window]
opacity = 0.85
blur = true

[font]
size = 11.0
EOF

echo "--- writing to mako config ---"
cat << 'EOF' > ~/.config/mako/config
background-color=#1e1e2e
text-color=#cdd6f4
border-color=#89b4fa
border-size=2
border-radius=5
font=monospace 10
EOF

echo "--- writing to hyprland config ---"
cat << 'EOF' >> ~/.config/hypr/hyprland.lua
hl.config({ autogenerated = false })
local mainMod = "SUPER"
local terminal = "alacritty"
local fileManager = "thunar"
local menu = "wofi --show drun"
hl.on("hyprland.start", function()
  hl.exec_cmd("waybar")
  hl.exec_cmd("mako")
  hl.exec_cmd("hyprpaper")
end)
EOF

echo "--- writing to fastfetch config ---"
cat << 'EOF' > ~/.config/fastfetch/config.jsonc
{
  "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/master/doc/json_schema.json",
  "modules": [
	"Title",
    "Separator",
	"Host",
	"Kernel",
	"Uptime",
	"Packages",
	"Shell",
	"Display",
	"WM",
	"TerminalFont",
  {
	  "type": "cpu",
		"temp": true,
		"format": "{1} ({3}) @ {7}"
  },
  {
		"type": "cpuusage",
		"format": "{1}" 
	},
	{
    "type": "gpu",
    "temp": true,
    "format": "{1} {2} @ {3}"
  },
  {
    "type": "gpuusage",
    "format": "{1}"
  },
  "Memory",
	"Disk",
	"Break",
	"Colors"
  ]
}
EOF

echo "=== System Configuration Complete! Please reboot ==="
